version: '3.9'

services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb://mongo:27017/artaround"
      MONGO_DB_NAME: "artaround"
    depends_on:
      - mongo

volumes:
  mongo_data:
